---
apiVersion: v1
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  hsts-include-subdomains: "false"
  body-size: "4096m"
  client_max_body_size: "4096m"
  proxy-body-size: "4096m"
  server-name-hash-bucket-size: "256"
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: p2c
  labels:
    app: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: p2c
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: p2c