---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: p1c-staging
  namespace: p2c
spec:
  secretName: p2c-staging-tls
  issuerRef:
    name: cert-manager-staging
  commonName: example.com
  dnsNames:
  - example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.com