---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: p2c-prod
  namespace: p2c
spec:
  secretName: p1c-prod-tls
  issuerRef:
    name: cert-manager
  commonName: example.com
  dnsNames:
  - example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.com